default: &default
  adapter: mysql2
  encoding: utf8
  database: bee
  pool: 5
  username: root
  password: 


development:
  <<: *default


test:
  <<: *default
  database: test_bee


production:
  <<: *default